name: Linux ARM (Docker/GStreamer)

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - cp_main

env:
  DEBIAN_FRONTEND: noninteractive
  OPENCV_VERSION: 4.6.0

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/setup-qemu-action@v1
          
      - name: Build with Docker
        run: |
          # Override OpenCV version in Dockerfile
          docker build \
            -t opencvsharp-linux-arm-gst:latest \
            --output=type=docker \
            --platform=linux/arm64 \
            --build-arg OPENCV_VERSION \
            ./docker/linux-arm64-gst
      - name: Extract build files from Docker instance
        run: |
          docker create -ti --name opencvsharp-linux-arm-gst-tmp opencvsharp-linux-arm-gst bash
          docker cp opencvsharp-linux-arm-gst-tmp:/artifacts .

      - name: Patch nuspec with version and build NuGet package
        run: |
          sed -E --in-place=.bak "s/<version>[0-9]\.[0-9]{1,2}\.[0-9]{1,2}.[0-9]{8}(-beta[0-9]*)?<\/version>/<version>${OPENCV_VERSION}.$(date '+%Y%m%d')<\/version>/" nuget/OpenCvSharp4.runtime.linux-arm.nuspec
          cp artifacts/libOpenCvSharpExtern.so nuget/
          dotnet pack nuget/OpenCvSharp4.runtime.linux-arm.csproj -o artifacts_arm

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts_linux_arm
          path: artifacts_arm
